<a href="https://colab.research.google.com/github/RendiZein/Metode-Rekayasa-Komputasi/blob/main/Python_In_Nutshell.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [99]:
import random
import numpy as np
import pandas as pd

# Latihan 1

# 1.1
Buatlah program yang meminta masukan berupa bilangan bulat kemudian menenentkan apakah bilangan tersebut adalah bilangan prima atau bukan.

In [77]:
def prime():
  try:
    x=int(input('Masukkan nilai x (bilangan bulat) ='))
    if 0<x<8:
      if x==2 or x==3 or x==5 or x==7:
        print('{} adalah bilangan prima'.format(x))
      else:
        print('{} bukan bilangan prima'.format(x))
    elif x<0: #antisipasi masukkan negatif
      print("Nilai yang dimasukkan harus bilangan bulat")
    else:
      if x%2==0 or x%3==0 or x%5==0 or x%7==0:
        print('{} bukan bilangan prima'.format(x))
      else:
        print('{} adalah bilangan prima'.format(x))
  except ValueError: #antisipasi masukkan string dan float
    print("Nilai yang dimasukkan harus bilangan bulat")

In [78]:
prime()

Masukkan nilai x (bilangan bulat) =23
23 adalah bilangan prima


### validasi

In [91]:
def prime(x):
  try:
    if 0<x<8:
      if x==2 or x==3 or x==5 or x==7:
        xp=1
        return x,xp
      else:
        xp=0
        return x,xp
    else:
      if x%2==0 or x%3==0 or x%5==0 or x%7==0:
        xp=0
        return x,xp
      else:
        xp=1
        return x,xp
  except ValueError:
    print("Nilai yang dimasukkan harus bilangan bulat")

In [92]:
prime_number=[]
for i in range(1,100):
  i,xp=prime(i)
  if xp==1:
    prime_number.append(i)



In [94]:
len(prime_number)

25

In [95]:
sde=[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
len(sde)

25

## 1.2
Buatlah program yang meminta masukan berupa string, kemudian mencetak hasil dengan urutan yang dibalik.

In [25]:
try:
  x=str(input())
  x_inv=x[::-1]#indexing '::' adalah stepping '-1' berarti stepping (melangkah) 1 kebelakang
  print("urutan dibaliknya adalah berikut \n{}".format(x_inv))
except ValueError: # cegah masukan bukan string
  print("Nilai yang dimasukkan harus string")


metode rekayasa komputasi
urutan dibaliknya adalah berikut 
isatupmok asayaker edotem


# Latihan 2
Buatlah fungsi yang mensimulasikan pelemparan dua buah dadu. Jalankan program untuk melempar dadu berulang kali (dengan pengulangan yang banyak) dan tulislah fraksi dari pelemparan yang menghasilkan jumlah dari setiap kombinasi yang mungkin terjadi, 2 - 12.

Improvement:
1. Buat dataframe
* kolom adalah jumlah mata dadu
* baris pertama hingga 7 adalah komputasi dengan pengulangan
baris

In [100]:
# pengulangan=int(input())
pengulangan=10000000000
prob={}
for i in range(2,13):
  prob[str(i)]=0
for i in range(pengulangan):
  d1=random.randint(1,6)
  d2=random.randint(1,6)
  d12=d1+d2
  prob[str(d12)]+= 1
for i in range(2,13):
  prob[str(i)]=prob[str(i)]/pengulangan

KeyboardInterrupt: 

In [98]:
prob

{'2': 0.02715,
 '3': 0.05461,
 '4': 0.08446,
 '5': 0.11069,
 '6': 0.13704,
 '7': 0.16785,
 '8': 0.1393,
 '9': 0.11174,
 '10': 0.08364,
 '11': 0.05503,
 '12': 0.02849}

In [102]:
print(6/36)

0.16666666666666666


# Latihan 3
Mintalah pengguna untuk memasukkan ukuran matriks, N. Cetaklah matriks acak berukuran N x N, kemudian cetak pula vektor yang berisi jumlahan dari masing-masing kolom.

In [86]:
N=int(input())
mat=np.random.uniform(low= -10, high= 10, size=(N,N))
print("Matrik awal adalah \n{}".format(mat))
mat_sum_col=mat.sum(axis=0)
print("Penjumlahan kolom matriks menghasilkan matriks berikut \n{}".format(mat_sum_col))

[[ 1.82456592 -4.78328392  8.80693525  9.45232579]
 [-8.82737724 -3.908188   -7.77906182 -7.05242082]
 [ 8.76361484  5.33265348 -1.10537719  9.10780048]
 [ 1.01683907 -2.34081724  6.10145251  0.4637892 ]]
[ 2.7776426  -5.69963568  6.02394875 11.97149465]


# Latihan 4
Buatlah dictionary yang berisi pasangan kunci:nilai, dengan key berisi nama partikel subatom yang umum (yaitu proton, neutron dan elektro) dan nilai berupa massa partikel dalam kilogram.

In [89]:
psa = {} #inisiasi dictionary
#isi setiap key dengan value
psa['proton']=1.67262192e-27
psa['neutron']=1.67492749804e-27
psa['elektron']=9.1093837e-31