<a href="https://colab.research.google.com/github/RendiZein/Metode-Rekayasa-Komputasi/blob/main/Simultaneous_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Nomor 21 (Cramer)

In [32]:
def cramer(mat, constant): # takes the matrix and the costants

    D = np.linalg.det(mat) # calculating the determinant of the original matrix

    # substitution of the column with costant and creating new matrix
    mat1 = np.array([constant, mat[:, 1], mat[:, 2]])
    mat2 = np.array([mat[:, 0], constant, mat[:, 2]])
    mat3 = np.array([mat[:, 0], mat[:, 1], constant])
    Dx = np.linalg.det([mat1, mat2, mat3])

    #calculatin determinant of the matrix
    Dx = np.linalg.det(mat1)
    Dy = np.linalg.det(mat2)
    Dz = np.linalg.det(mat3)

    #finding the X1, X2, X3
    y1 = Dx/D
    y2 = Dy/D
    y3 = Dz/D

    print("Nilai y1 adalah {}".format(round(y1,5)))
    print("Nilai y2 adalah {}".format(round(y2,5)))
    print("Nilai y3 adalah {}".format(round(y3,5)))

## Soal

In [33]:
a_soal = np.array([[15., -2., 10.],
             [-16., 13., -22.],
             [27., -18., -12.]])

b_soal = np.array([54., -44., -3.])
cramer(a_soal,b_soal)

Nilai y1 adalah 2.80376
Nilai y2 adalah 3.15536
Nilai y3 adalah 1.82543


## Contoh

In [39]:
a = np.array([[5., -1., 10.],
             [-6., 3., 22.],
             [7., -8., -12.]])

b = np.array([-17., 23., -52.])
cramer(a,b)

Nilai y1 adalah -2.01802
Nilai y2 adalah 5.01802
Nilai y3 adalah -0.18919


In [41]:

print("Matrix a adalah\n{}".format(a))

Matrix a adalah
[[  5.  -1.  10.]
 [ -6.   3.  22.]
 [  7.  -8. -12.]]


# Nomor 22 (eliminasi Gauss-Naif )

In [48]:
def egn(a,b,pr):
  # eliminasi subtitusi baris 2 dan 3
  n_baris,n_kolom=a.shape
  a1=np.zeros(a.shape)
  b1=np.zeros(b.shape)
  a_view=a
  b_view=b
  ## Iterasi setiap baris
  for j in range(1,n_baris):
    ### iterasi setiap kolom
    for k in range(n_kolom):
      ### hitung a[j,k]
      a1[j,k]=a[j,k]-(a[j,0]/a[0,0])*a[0,k]
    ## hitung b[j]
    b1[j]=b[j]-(a[j,0]/a[0,0])*b[0]
  a_view[1]=a1[1]
  b_view[1]=b1[1]
  a_view[2]=a1[2]
  b_view[2]=b1[2]
  if pr==2:
    print("Matrix hasil substitusi baris 2 dan 3")
    print("Matrix a adalah\n{}".format(a_view))
    print("Matrix b adalah\n{}\n\n".format(b_view))
  # eliminasi subtitusi baris 3
  a2=np.zeros(a.shape)
  b2=np.zeros(b.shape)
  for j in range(2,n_baris):
    ## iterasi setiap kolom
    for k in range(n_kolom):
      ## hitung a[j,k]
      a2[j,k]=a1[j,k]-(a1[j,1]/a1[1,1])*a1[1,k]
      ## hitung b[j]
      b2[j]=b1[j]-(a1[j,1]/a1[1,1])*b1[1]
  # masukkan nilai baru pada matrix a dan b
  a[1]=a1[1]
  b[1]=b1[1]
  a[2]=a2[2]
  b[2]=b2[2]
  if pr==2:
    print("Matrix hasil operasi")
    print("Matrix a adalah\n{}".format(a))
    print("Matrix b adalah\n{}\n\n".format(b))
  # hitung y3
  y3=b[2]/a[2,2]
  # hitung y2
  y2=(b[1]-a[1,2]*y3)/a[1,1]
  # hitung y1
  y1=(b[0]-y2*a[0,1]-a[0,2]*y3)/a[0,0]
  if pr==2:
    print("Nilai y1 adalah {}".format(round(y1,5)))
    print("Nilai y2 adalah {}".format(round(y2,5)))
    print("Nilai y3 adalah {}".format(round(y3,5)))
  if pr==1:
    return a,b

## Soal

In [51]:
a_soal = np.array([[15., -2., 10.],
             [-16., 13., -22.],
             [27., -18., -12.]])

b_soal = np.array([54., -44., -3.])
egn(a_soal,b_soal,pr=2)

Matrix hasil substitusi baris 2 dan 3
Matrix a adalah
[[ 15.          -2.          10.        ]
 [  0.          10.86666667 -11.33333333]
 [  0.         -14.4        -30.        ]]
Matrix b adalah
[  54.    13.6 -100.2]


Matrix hasil operasi
Matrix a adalah
[[ 15.          -2.          10.        ]
 [  0.          10.86666667 -11.33333333]
 [  0.           0.         -45.01840491]]
Matrix b adalah
[ 54.          13.6        -82.17791411]


Nilai y1 adalah 2.80376
Nilai y2 adalah 3.15536
Nilai y3 adalah 1.82543


## Contoh

In [52]:
a = np.array([[5., -1., 10.],
             [-6., 3., 22.],
             [7., -8., -12.]])

b = np.array([-17., 23., -52.])
egn(a,b,pr=2)

Matrix hasil substitusi baris 2 dan 3
Matrix a adalah
[[  5.   -1.   10. ]
 [  0.    1.8  34. ]
 [  0.   -6.6 -26. ]]
Matrix b adalah
[-17.    2.6 -28.2]


Matrix hasil operasi
Matrix a adalah
[[ 5.         -1.         10.        ]
 [ 0.          1.8        34.        ]
 [ 0.          0.         98.66666667]]
Matrix b adalah
[-17.           2.6        -18.66666667]


Nilai y1 adalah -2.01802
Nilai y2 adalah 5.01802
Nilai y3 adalah -0.18919


# Nomor 23 (Gauss-Jordan)

In [56]:
def gj (a,b):
  # membuat matriks diagonal bernilai 1
  for i in range(3):
    b[i]=b[i]/a[i,i]
    a[i]=a[i]/a[i,i]
  print("Matrix a adalah\n{}".format(a))
  print("Matrix b adalah\n{}\n\n".format(b))
  #nilai pada baris 2 semua nol kecuali kolom 2
  b[1]=b[1]-a[1,2]*b[2]
  a[1,2]=a[1,2]-a[1,2]*a[2,2]
  print("Matrix a adalah\n{}".format(a))
  print("Matrix b adalah\n{}\n\n".format(b))
  #nilai pada baris 1 semua nol kecuali kolom 1
  b[0]=b[0]-a[0,2]*b[2]
  a[0,2]=a[0,2]-a[0,2]*a[2,2]
  print("Matrix a adalah\n{}".format(a))
  print("Matrix b adalah\n{}\n\n".format(b))
  b[0]=b[0]-a[0,1]*b[1]
  a[0,1]=a[0,1]-a[0,1]*a[1,1]
  print("Matrix a adalah\n{}".format(a))
  print("Matrix b adalah\n{}\n\n".format(b))
  y3=b[2]
  y2=b[1]
  y1=b[0]
  print("Nilai y1 adalah {}".format(round(y1,5)))
  print("Nilai y2 adalah {}".format(round(y2,5)))
  print("Nilai y3 adalah {}".format(round(y3,5)))

## Soal

In [57]:
a_soal = np.array([[15., -2., 10.],
             [-16., 13., -22.],
             [27., -18., -12.]])

b_soal = np.array([54., -44., -3.])
a_soal,b_soal=egn(a_soal,b_soal,pr=1)

In [58]:
gj(a_soal,b_soal)

Matrix a adalah
[[ 1.         -0.13333333  0.66666667]
 [ 0.          1.         -1.04294479]
 [-0.         -0.          1.        ]]
Matrix b adalah
[3.6        1.25153374 1.82542927]


Matrix a adalah
[[ 1.         -0.13333333  0.66666667]
 [ 0.          1.          0.        ]
 [-0.         -0.          1.        ]]
Matrix b adalah
[3.6        3.15535568 1.82542927]


Matrix a adalah
[[ 1.         -0.13333333  0.        ]
 [ 0.          1.          0.        ]
 [-0.         -0.          1.        ]]
Matrix b adalah
[2.38304715 3.15535568 1.82542927]


Matrix a adalah
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0. -0.  1.]]
Matrix b adalah
[2.80376124 3.15535568 1.82542927]


Nilai y1 adalah 2.80376
Nilai y2 adalah 3.15536
Nilai y3 adalah 1.82543


## Contoh

In [59]:
a,b=egn(a,b,pr=1)

In [60]:
gj (a,b)

Matrix a adalah
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matrix b adalah
[-2.01801802  5.01801802 -0.18918919]


Matrix a adalah
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matrix b adalah
[-2.01801802  5.01801802 -0.18918919]


Matrix a adalah
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matrix b adalah
[-2.01801802  5.01801802 -0.18918919]


Matrix a adalah
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matrix b adalah
[-2.01801802  5.01801802 -0.18918919]


Nilai y1 adalah -2.01802
Nilai y2 adalah 5.01802
Nilai y3 adalah -0.18919
