<a href="https://colab.research.google.com/github/RendiZein/Metode-Rekayasa-Komputasi/blob/main/T01_530067.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Latihan pemrograman

Susunlah program menggunakan Python untuk pertanyaan-pertanyaan di bawah ini. Kerjakan langsung pada ruang yang disediakan di bawah masing-masing pertanyaan. Unggah kembali hasil pekerjaan Anda dalam bentuk file Jupyter Notebook dengan format nama file `T01-XXXXXX` di mana `XXXXXX` adalah NIU Anda.







In [65]:
import numpy as np
import pandas as pd
from math import sqrt, factorial
import random
from numpy.linalg import inv

## Nomor 1
1. Tuliskan perintah berikut dan jelaskan hasilnya
- `round(np.pi,8)` dan `round(np.pi,7)`
-  `2**3**4` dan `(2**3)**4`
- `np.arctan(1.5)` dan `np.arctan2(−3.,−2.)`

### Jawab

In [6]:
a_1=round(np.pi,8)
a_2=round(np.pi,7)
b_1=2**3**4
b_2=(2**3)**4
c_1=np.arctan(1.5)
c_2=np.arctan2(-3.,-2.)
print(a_1, a_2)
print(b_1, b_2)
print(c_1, c_2)

3.14159265 3.1415927
2417851639229258349412352 4096
0.982793723247329 -2.158798930342464


### Penjelasan

In [9]:
help(np.arctan2)

Help on ufunc:

arctan2 = <ufunc 'arctan2'>
    arctan2(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Element-wise arc tangent of ``x1/x2`` choosing the quadrant correctly.
    
    The quadrant (i.e., branch) is chosen so that ``arctan2(x1, x2)`` is
    the signed angle in radians between the ray ending at the origin and
    passing through the point (1,0), and the ray ending at the origin and
    passing through the point (`x2`, `x1`).  (Note the role reversal: the
    "`y`-coordinate" is the first function parameter, the "`x`-coordinate"
    is the second.)  By IEEE convention, this function is defined for
    `x2` = +/-0 and for either or both of `x1` and `x2` = +/-inf (see
    Notes for specific values).
    
    This function is not defined for complex-valued arguments; for the
    so-called argument of complex values, use `angle`.
    
    Parameters
    ----------
    x1 : array_like, real-valued
      

In [8]:
help(np.arctan)

Help on ufunc:

arctan = <ufunc 'arctan'>
    arctan(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Trigonometric inverse tangent, element-wise.
    
    The inverse of tan, so that if ``y = tan(x)`` then ``x = arctan(y)``.
    
    Parameters
    ----------
    x : array_like
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized 

In [7]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



## Nomor 2
2. Diketahui akar dari persamaan kuadratik $ax^2 + bx + c = 0$ adalah

$$x_1 = \dfrac{-b + \sqrt{b^2-4ac}}{2a}, \quad x_2 = \dfrac{-b - \sqrt{b^2-4ac}}{2a} $$

Apakah program di bawah ini sudah betul ? Jika belum, perbaiki program tersebut sehingga memberikan hasil yang benar.

```Python
a = 2; b = 1; c = 2
from math import sqrt
q = b*b - 4*a*c
q_sr = sqrt(q)
x1 = (-b + q_sr)/2*a
x2 = (-b - q_sr)/2*a
print x1, x2
```

In [15]:
a = 2; b = 1; c = 2
from math import sqrt
q = b*b - 4*a*c
q_sr = sqrt(q)
x1 = (-b + q_sr)/2*a
x2 = (-b - q_sr)/2*a
# print x1, x2

ValueError: math domain error

In [13]:
a = 2; b = 1; c = 2
from math import sqrt
q = b*b - 4*a*c
q_sr = sqrt(np.abs(q))
x1 = (-b + q_sr)/2*a
x2 = (-b - q_sr)/2*a
print x1, x2

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (<ipython-input-13-5dd60e7d0854>, line 7)

In [16]:
a = 2; b = 1; c = 2
from math import sqrt
q = b*b - 4*a*c
q_sr = sqrt(np.abs(q))
x1 = (-b + q_sr)/2*a
x2 = (-b - q_sr)/2*a
print(x1, x2)

2.872983346207417 -4.872983346207417


### Penjelasan

1. `math domain error` Fungsi `sqrt()` tidak menerima masukan berupa bilangan negatif. Sehingga masukkannya harus dimutlakkan
2. `SyntaxError` Perintah `print x1, x2` memerlukan

In [ ]:
help(sqrt)

Help on built-in function sqrt in module math:

sqrt(x, /)
    Return the square root of x.



## Nomor 3
3. Buatlah program yang meminta masukan berupa bilangan bulat kemudian menentukan apakah bilangan tersebut adalah bilangan prima atau bukan.

In [17]:
def prime():
  try:
    x=int(input('Masukkan nilai x (bilangan bulat) ='))
    if 0<x<8:
      if x==2 or x==3 or x==5 or x==7:
        print('{} adalah bilangan prima'.format(x))
      else:
        print('{} bukan bilangan prima'.format(x))
    elif x<0: #antisipasi masukkan negatif
      print("Nilai yang dimasukkan harus bilangan bulat")
    else:
      if x%2==0 or x%3==0 or x%5==0 or x%7==0:
        print('{} bukan bilangan prima'.format(x))
      else:
        print('{} adalah bilangan prima'.format(x))
  except ValueError: #antisipasi masukkan string dan float
    print("Nilai yang dimasukkan harus bilangan bulat")

### Jawab

In [19]:
prime()

Masukkan nilai x (bilangan bulat) =2
2 adalah bilangan prima


### Penjelasan

In [20]:
def prime_validation(x):
  try:
    if 0<x<8:
      if x==2 or x==3 or x==5 or x==7:
        xp=1
        return x,xp
      else:
        xp=0
        return x,xp
    else:
      if x%2==0 or x%3==0 or x%5==0 or x%7==0:
        xp=0
        return x,xp
      else:
        xp=1
        return x,xp
  except ValueError:
    print("Nilai yang dimasukkan harus bilangan bulat")

In [21]:
prime_number=[]
for i in range(1,100):
  i,xp=prime_validation(i)
  if xp==1:
    prime_number.append(i)
len(prime_number)

25

## Nomor 4
4. Jika kita membuat daftar bilangan di bawah 10 yang merupakan kelipatan dari 3 atau 7, kita akan memperoleh angka 3, 6, 7 dan 9. Jumlahan dari bilangan-bilangan tersebut adalah 25. Carilah jumlahan dari semua bilangan kelipatan 3 atau 7 di bawah 10000.

### Jawab

In [ ]:
def nomor4(n):
  lt=[]
  for i in range(n):
    if i%3==0 or i%7==0:
      lt.append(i)
  lt_sum=np.sum(lt)
  print(lt_sum)

### Penjelasan

In [ ]:
nomor4(10000)

21426429


In [ ]:
nomor4(10)

25


## Nomor 5
5. Buatlah program yang meminta masukan berupa string, kemudian mencetak hasil dengan urutan yang dibalik.

### Jawab

In [ ]:
try:
  x=str(input())
  x_inv=x[::-1]#indexing '::' adalah stepping '-1' berarti stepping (melangkah) 1 kebelakang
  print("urutan dibaliknya adalah berikut \n{}".format(x_inv))
except ValueError: # cegah masukan bukan string
  print("Nilai yang dimasukkan harus string")

## Nomor 6
6. Deret

$$\frac{1}{0!} + \frac{1}{1!} + \frac{1}{2!} + \frac{1}{3!} + \frac{1}{4!} + \frac{1}{5!} + \ldots = e$$

merupakan cara untuk melakukan pendekatan terhadap nilai *e* berdasar ekspansi Taylor dari $e^x$. Kita bisa menuliskan penjumlahan parsial sebagai

$$e_{pendekatan} = \sum_{i=0}^N \frac{1}{i!}$$

Dengan menggunakan kalang `for`, hitung pendekatan untuk *e* menggunakan

$$N = 1,2,3,4,5,6,7,8,9,10,100,1000,10000$$

Nilai N mana yang memberikan nilai paling dekat dengam e

In [31]:
parsial_sum_n=[]
n_list=[1,2,3,4,5,6,7,8,9,10,100,1000,10000]
list_taylor=[[1/factorial(i) for i in range(n+1)]for n in n_list]
for j in list_taylor:
  parsial_sum_n.append(sum(j))
print(parsial_sum_n)

[2.0, 2.5, 2.6666666666666665, 2.708333333333333, 2.7166666666666663, 2.7180555555555554, 2.7182539682539684, 2.71827876984127, 2.7182815255731922, 2.7182818011463845, 2.7182818284590455, 2.7182818284590455, 2.7182818284590455]


In [34]:
exp=np.exp(1)
error=[np.abs(i-exp)/exp for i in parsial_sum_n]
error

[0.26424111765711533,
 0.08030139707139415,
 0.018988156876153812,
 0.003659846827343768,
 0.0005941848175817597,
 8.324114928800986e-05,
 1.0249196674547021e-05,
 1.125202597843745e-06,
 1.1142547828265698e-07,
 1.0047766310211053e-08,
 1.6337129034990842e-16,
 1.6337129034990842e-16,
 1.6337129034990842e-16]

## Nomor 7
7. Buatlah fungsi yang mensimulasikan pelemparan dua buah dadu. Jalankan program untuk melempar dadu berulang kali (dengan pengulangan yang banyak) dan tulislah fraksi dari pelemparan yang menghasilkan jumlah dari setiap kombinasi yang mungkin terjadi, 2 - 12.


In [37]:
# pengulangan=int(input())
pengulangan=100
prob={}
for i in range(2,13):
  prob[str(i)]=0
for i in range(pengulangan):
  d1=random.randint(1,6)
  d2=random.randint(1,6)
  d12=d1+d2
  prob[str(d12)]+= 1
for i in range(2,13):
  prob[str(i)]=prob[str(i)]/pengulangan

In [38]:
prob

{'2': 0.04,
 '3': 0.01,
 '4': 0.08,
 '5': 0.15,
 '6': 0.15,
 '7': 0.17,
 '8': 0.1,
 '9': 0.15,
 '10': 0.11,
 '11': 0.03,
 '12': 0.01}

## Nomor 8
8. Mintalah pengguna untuk memasukkan bilangan, _N_. Cetaklah matriks acak berukuran _N_ x _N_, kemudian cetak pula vektor yang berisi jumlahan dari masing-masing kolom.

In [ ]:
N=int(input())
mat=np.random.uniform(low= -10, high= 10, size=(N,N))
print("Matrik awal adalah \n{}".format(mat))
mat_sum_col=mat.sum(axis=0)
print("Penjumlahan kolom matriks menghasilkan matriks berikut \n{}".format(mat_sum_col))

## Nomor 9
9. Buatlah *dictionary* yang berisi pasangan `kunci:nilai` di mana kunci adalah nama-nama partikel elementer dan nilai adalah massa partikel tersebut dalam satuan kilogram.

In [ ]:
psa = {} #inisiasi dictionary
#isi setiap key dengan value
psa['proton']=1.67262192e-27
psa['neutron']=1.67492749804e-27
psa['elektron']=9.1093837e-31
print(psa)

## Nomor 10
10. Bahan padat akan mengalami pemuaian jika suhunya meningkat. Besarnya pemuaian tersebut dapat dinyatakan sebagai berikut

$$ \Delta L = \alpha \Delta T L$$

dengan $\Delta L$ adalah perubahan panjang, $\alpha$ adalah koefisien muai linear, $\Delta T$ adalah perubahan suhu dan $L$ adalah panjang bahan pada suhu awal, $T$.

Tabel di bawah ini menampilkan koefisien muai beberapa bahan.

|Material   | Koefisien muai $\times 10^6$ m/[m.$^\circ$C]|
|------:    |-------------------------------------------: |
|Tembaga    |16                                           |
|Aluminium  |22,5                                         |
|Kaca       |5,9                                          |
|Baja       |11,5                                         |
|Polietilen | 125                                         |

Buatlah fungsi Python bernama `muai` yang memiliki argumen input berupa jenis bahan (string teks), perubahan suhu dan panjang awal. Fungsi tersebut akan mengembalikan panjang bahan setelah memuai. Uji fungsi Anda dengan beberapa contoh kasus.

In [41]:
dict_material={'Tembaga':16, 'Aluminium':22.5, 'Kaca':5.9, 'Baja':11.5, 'Polietilen':125}
material=str(input("Materi apa yang akan dihitung (Tembaga/Aluminium/Kaca/Polietilen) :"))
delta_t=int(input("Berapa perubahan suhu ?"))
panjang_awal=int(input("Berapa panjang awal ?"))
alpha=dict_material[material]
delta_l=alpha*delta_t*panjang_awal
print("Perubahan panjang {} (10^-6 m)".format(delta_l))

Materi apa yang akan dihitung (Tembaga/Aluminium/Kaca/Polietilen) :Tembaga
Berapa perubahan suhu ?36
Berapa panjang awal ?39
Perubahan panjang 22464 (10^-6 m)


## Nomor 11
11. Tulislah fungsi bernama `split_function(f,g,a,b,x)` di mana `f` dan `g` adalah fungsi `f(x)` dan `g(x)`. Outputnya adalah `f(x)` jika $x\le a$, `g(x)` jika $x\ge b$, dan 0 untuk nilai $x$ lainnya. Anggap bahwa $b>a$.

In [70]:
def split_function(f,g,a,b,x):
    # tulis kode fungsi di sini
    if b>a:
      if x<=a:
        return round(f(x),4)
      elif x>=b:
        return round(g(x),4)
      else:
        return 0
    else:
      print("Masukkan nila yang benar (b>a)")



In [71]:
# output : 2.713
split_function(np.exp, np.sin, 2, 4, 1)

2.7183

In [72]:
# output : 0
split_function(np.exp, np.sin, 2, 4, 3)

0

In [73]:
# output : -0.9589
split_function(np.exp, np.sin, 2, 4, 5)

-0.9589

## Nomor 12
12. Perhatikan fungsi berikut ini

$$ y(x) = \sqrt{\dfrac{100(1-0.01x^2)^2 + 0.02x^2}{(1-x^2)^2+0.1x^2}} $$

Buatlah subplot berukuran $2\times 2$ untuk menampilkan $y(x)$ pada rentang $0 \le x \le 100$ menggunakan `plot`, `semilogx`, `semilogy` dan `loglog`. Gunakan diskretisasi $x$ yang cukup rapat agar plot terlihat mulus. Tambahkan label sumbu dan judul di masing-masing plot. Tampilkan grid. Plot manakah yang tampaknya mampu untuk menyampaikan paling banyak informasi?

In [ ]:
y = lambda x: (100*()**2+0.02*(x**2))/((1-x**2)**2+0.1(x**2))


## Nomor 13
13. Ubahlah array berikut ini

```Python
[0 1 2 3 4 5 6 7 8]
```

menjadi

```Python
[[0, 1, 2]
 [3, 4, 5]
 [6, 7, 8]]
```

In [60]:
mat=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
print(mat)
mat_reshaped=np.reshape(mat, (3,3))
print(mat_reshaped)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Nomor 14
14. Buatlah script Python untuk menentukan inverse dari matriks berikut ini

$$ \begin{bmatrix}
1.13 & 3.83 & 1.16 & 3.40\\
0.53 & 1.79 & 2.53 & 1.54 \\
3.41 & 4.93 & 8.76 & 1.31 \\
1.24 & 4.99 & 10.67 & 0.02
\end{bmatrix} $$

Pada script yang dibuat, tuliskan juga pengujian inverse matriks tersebut dengan mengalikannya dengan matriks asal dan hasilnya  mendekati matriks identitas.

In [79]:
mat=np.transpose(np.reshape([1.13,0.53,3.41,1.24,3.83,1.79,4.93,4.99,1.16,2.53,8.76,10.67,3.40,1.54,1.31,0.02], (4,4)))
mat_inv=inv(mat)
mat_id=np.identity(4).astype(int)
mul=np.matmul(mat,mat_inv).astype(int)
print(mat)
print(mat_inv)
print(mul)
print(mat_id)
print(mul==mat_id)
print(np.matmul(mat,mat_inv))

[[ 1.13  3.83  1.16  3.4 ]
 [ 0.53  1.79  2.53  1.54]
 [ 3.41  4.93  8.76  1.31]
 [ 1.24  4.99 10.67  0.02]]
[[-0.07829101 -0.22514192  0.47285055 -0.32631154]
 [ 0.5333038  -1.08340824 -0.11500059  0.29332667]
 [-0.23993721  0.53074973 -0.00111876 -0.00512364]
 [-0.19875222  1.11417477 -0.0272268  -0.2202252 ]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False  True]
 [ True  True  True  True]]
[[ 1.00000000e+00  1.67494927e-16 -3.71334699e-17 -6.92579151e-17]
 [-7.20091442e-17  1.00000000e+00 -2.57391414e-17  5.49870556e-18]
 [ 1.14030889e-16  2.99183333e-16  1.00000000e+00 -1.02774244e-16]
 [-3.43939635e-16 -6.33624759e-18 -6.61736888e-17  1.00000000e+00]]


## Nomor 15
15. Unduh file `.csv` dari [https://gml.noaa.gov/webdata/ccgg/trends/co2/co2_annmean_gl.csv](https://gml.noaa.gov/webdata/ccgg/trends/co2/co2_annmean_gl.csv). Data tersebut berisi rekaman konsentrasi CO$_2$ (dalam ppm) di atmosfer. Tulislah script Python yang membaca/mengimpor data tersebut dan buatlah plot untuk menampilkannya.

In [ ]:
import pandas as pd
df=pd.read_csv("https://gml.noaa.gov/webdata/ccgg/trends/co2/co2_annmean_gl.csv")
df

ParserError: Error tokenizing data. C error: Expected 1 fields in line 8, saw 2
